source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ProjectZXC' do
  use_frameworks!
  pod 'Firebase'
  pod 'Google-Mobile-Ads-SDK', '~> 7.9'
  pod 'Flurry-iOS-SDK/FlurrySDK'
end